# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KS_Tp23onpqjpCyXkog_8JB_rAaspe1
"""

import rx
from rx import operators as ops
from rx.subject import Subject

# Creación de un Subject que actúa como una fuente de eventos
user_stream = Subject()

def new_user_notification(user):
    print(f"[Notificación] Nuevo usuario conectado: {user}")

# Nos suscribimos al flujo de eventos
user_stream.pipe(
    ops.map(lambda user: user.upper())  # Transformamos el nombre del usuario a mayúsculas
).subscribe(new_user_notification)

# Simulación de usuarios conectándose
user_stream.on_next("ALPHA")
user_stream.on_next("BRAVO")
user_stream.on_next("ChARLIE")